# https://taskfile.dev

version: "3"

vars:
  APP: fibonachicken

tasks:
  default:
    cmds:
      - task: install:prereqs
      - task: install:deps

  install:prereqs:
    desc: Installs prerequisites
    cmds:
      - brew bundle
    sources:
      - Brewfile
    preconditions:
      - sh: command -v brew
        msg: "Please install Homebrew: https://brew.sh/"

  install:deps:
    desc: Installs dependencies
    run: once
    cmds:
      - cmd: asdf plugin add dart
        ignore_error: true
      - cmd: asdf plugin add flutter
        ignore_error: true
      - asdf install
      - asdf current
    sources:
      - .tool-versions

  build:web:
    desc: Build Web Application with release mode
    cmds:
      - flutter build web --release --no-tree-shake-icons
    sources:
      - web/**/*
      - lib/**/*

  run:web:
    desc: Run Web Application
    cmds:
      - npx http-server build/web

  watch:web:
    desc: Watch, Build and Run Web Application (It's slow)
    cmds:
      - npx concurrently
          --names "BUILD,SERVER"
          "npx nodemon --watch lib --ext dart --exec \"task build:web\""
          "task run:web"
